#!/bin/bash

if [ $(ps -e|grep isvndashboard_mac|wc -l) -gt 3 ]; then 
    echo "More than 1 instance [ $(ps -e|grep isvndashboard_mac|wc -l) ]"
    exit
fi

SOURCE_PATH="`dirname \"$0\"`"

cd "$SOURCE_PATH/testing"
ctest -D Continuous
